chain_id_test:
  validators:
    - coins: 10cro
      staked: 10cro
    - coins: 10cro
      staked: 10cro
  accounts:
    - name: signer1
      coins: 10000cro
    - name: signer2
      coins: 2000cro
  genesis:
    app_state:
      staking:
        params:
          unbonding_time: "10s"
      gov:
        voting_params:
          voting_period: "10s"
        deposit_params:
          max_deposit_period: "10s"
          min_deposit:
            - denom: "basecro"
              amount: "10000000"
